# Generated by Django 5.2.1 on 2025-12-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boutique', '0002_avis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est active'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='Boutique.categorie', verbose_name='Catégorie Parent'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(blank=True, help_text="Clé unique utilisée dans l'URL (ex: electronique-telephones).", max_length=100, unique=True, verbose_name='Slug (URL Friendly)'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description détaillée (SEO)'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='icon',
            field=models.CharField(default='fas fa-folder', max_length=50, verbose_name='Icône (Classe FontAwesome)'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom de la Catégorie'),
        ),
    ]
